### ISSUE TITLE
Reid can not work

### ISSUE THREAD

**Issue by hahapt** [ymzis69/HybirdSORT#4]
When I try to infer demo with reid by:
`python3 tools/demo_track.py --demo_type image -f exps/example/mot/yolox_dancetrack_val_hybird_sort_reid.py -c pretrained/bytetrack_dance_model.pth.tar --fp16 --fuse --save_result`

I foud a wrong information:
Skip loading parameter 'heads.weight' to the model due to incompatible shapes: (12353, 2048) in the checkpoint but (0, 2048) in the model! You might want to double check if this is expected.

I have already download reid model and yolox model, and I found the reid features always be [0. ,0. ,0. ... 0.]

**Comment by HanGuangXin** [comment]
@hahapt Hi, it is normal, and there's no need to worry about it. The 'heads.weight' in reid weights refers to the **classifier**, which is utilized for training on the close set with pre-defined IDs. However, when referencing, the classifier can simply be dropped since we solely require the reid model to extract appearance features.

**Comment by hahapt** [comment]
> @hahapt Hi, it is normal, and there's no need to worry about it. The 'heads.weight' in reid weights refers to the **classifier**, which is utilized for training on the close set with pre-defined IDs. However, when referencing, the classifier can simply be dropped since we solely require the reid model to extract appearance features.

Thanks, I got it.

**Comment by HanGuangXin** [comment]
And regarding the appearance features [0., 0., 0., ..., 0.], could you please test them on MOT17-val dataset using the corresponding models? Alternatively, could you provide the replicated results for DanceTrack-val? @hahapt

**Comment by HanGuangXin** [comment]
Quantified results are highly preferred as they provide us with the necessary information to effectively address this matter.

**Comment by HanGuangXin** [comment]
The issue is now closed. However, please don't hesitate to reopen it if you have any additional questions.
