### ISSUE TITLE
The usage of Reid module

### ISSUE THREAD

**Issue by hahapt** [ymzis69/HybirdSORT#5]
Is there any thing need to notice when use Reid module?
I try to do tracking in my own datasets, and I found the performance for HybirdSort are always a little better than HybirdSort+reid. In my own datasets, person are wear with different clothes so I cannot figure out why it happened.

**Comment by HanGuangXin** [comment]
Hi @hahapt, the ReID model used by each dataset is specifically trained with its training set, which means that its performance on unseen scenarios cannot be guaranteed.

**Comment by hahapt** [comment]
> Hi @hahapt, the ReID model used by each dataset is specifically trained with its training set, which means that its performance on unseen scenarios cannot be guaranteed.

Thanks. I found here are several parameters to control the HybirdSort Tracker, but no one is relevant to frame rate. Is there any parameter similar to the 'max_time_lost' in Bytetrack that can be change when the frame rate changes?

**Comment by ymzis69** [comment]
You can find this parameter in line 285 in 'trackers/hybird_sort_tracker/hybird_sort.py' and modify it. 'max_age' represents the maximum duration a target is allowed to remain undetected before being considered disappeared.

`class Hybird_Sort(object):
    def __init__(self, args, det_thresh, max_age=30, min_hits=3,
        iou_threshold=0.3, delta_t=3, asso_func="iou", inertia=0.2, use_byte=False):`

**Comment by ymzis69** [comment]
Depending on the context of your dataset usage, you can utilize alternative parameters or ReID models for tracking. For instance, in typical motion scenarios, you can employ parameters and ReID model for the MOT17 dataset.

`
python3 tools/demo_track.py --demo_type image -f exps/example/mot/yolox_x_mix_det_hybird_sort_reid.py -c pretrained/ocsort_x_mot17.pth.tar --path ./datasets/dancetrack/val/dancetrack0079/img1 --fp16 --fuse --save_result
`

**Comment by hahapt** [comment]
Thanks.
