### ISSUE TITLE
Problem with onnxruntime==1.8.0 when running repository on Colab

### ISSUE THREAD

**Issue by JFMeyer2k** [ymzis69/HybirdSORT#6]
Running your repository on Colab runs into an error when requirements are being installed:

ERROR: Could not find a version that satisfies the requirement onnxruntime==1.8.0 (from versions: 1.12.0, 1.12.1, 1.13.1, 1.14.0, 1.14.1, 1.15.0, 1.15.1)
ERROR: No matching distribution found for onnxruntime==1.8.0

Is it possible to use another version of onnxruntime?

**Comment by ymzis69** [comment]
"onnxruntime" is designed to convert PT models into ONNX models. If you don't need to deploy ONNX models, you can choose not to install "onnxruntime" or install a different version of the "onnxruntime".
