### ISSUE TITLE
Possibility to use YoloV7 and for multi-class setting?

### ISSUE THREAD

**Issue by JFMeyer2k** [ymzis69/HybirdSORT#8]
Is it possible to use YoloV7 (official repository: https://github.com/WongKinYiu/yolov7/tree/main) instead of YoloX?

Furthermore, (irrespective of using YoloX or YoloV7) I have a custom-trained object detector with two classes, and I would like to run the tracking on each class individually (multi-class tracking) as it avoids label switching between classes. Is there a possibility to run HybridSORT in a multi-class setting?

**Comment by ymzis69** [comment]
Currently, migrating the model to YOLOv8 is not within our plans. If you're interested in migrating to a multi-class tracking algorithm, you can refer to this repository: [MCMOT](https://github.com/CaptainEven/MCMOT-ByteTrack). You can set up a tracker for each category, and this can be achieved without much difficulty.

**Comment by HanGuangXin** [comment]
@JFMeyer2k Here are some small tips for multi-class setting, hope that they are helpful for your task. Firstly, in cases where the boxes of two classes differ significantly (such as person and car), or when the predicted class labels are inconsistent across different frames, you may consider ignoring the class label and adopting the single-class setting. Secondly, if you prefer not to perform association across different classes, you can generate a binary mask for the costs using a method like `t_labels[None, :] == d_labels[:, None]`.

**Comment by HanGuangXin** [comment]
Closing the issue. Please feel free to reopen if there are further questions.

**Comment by mikel-brostrom** [comment]
I made HybridSORT into a pluggable component for object detectors here: https://github.com/mikel-brostrom/yolo_tracking @JFMeyer2k. It also supports multi-class tracking.
