### ISSUE TITLE
CX2, CY2 = tracks[:,0], tracks[:,1] IndexError: index 1 is out of bounds for axis 1 with size 1

### ISSUE THREAD

**Issue by mikel-brostrom** [ymzis69/HybirdSORT#9]
I am feeding Yolov8 detections to HybridSORT but I get the following error:

> IndexError: index 1 is out of bounds for axis 1 with size 1

here:

https://github.com/ymzis69/HybirdSORT/blob/6101e1b225cb4b860f914049f9cccc0cd4538075/trackers/hybird_sort_tracker/association.py#L433

Am I missing something obvious?

**Comment by RaffelRavionaldo** [comment]
Hello, may i know how to use yolov8 for this hybridsort trackers?
